### ISSUE TITLE
Tipos de dados

### ISSUE THREAD

**Issue by profRenatoOliveira1** [TiagoSousaF/EliteCar-FrontEnd#1]
Tiago, seu arquivo `cadastro-carros.html` tem um `input` onde o usuário irá informar o ano de fabricação do carro, esse `input` você colocou o tipo `text`, mas ele deve ser do tipo `number` pois não deve aceitar nenhum caractere que não seja um número.

Portanto, troque isso
`<input type="text" name="input-ano-carro" placeholder="Insira o ano de fabricação" required>`

por isso
`<input type="number" name="input-ano-carro" placeholder="Insira o ano de fabricação" required>`

Aproveite e renomeie seu arquivo de `cadastro-carros.html` para `cadastro-carro.html`

**Comment by profRenatoOliveira1** [comment]
Tiago, no seu arquivo `cadastro-pedido.html`, o `input` onde o usuário vai informar a data do pedido, esse `input` deve ser do tipo `date`.

Portanto, troque isso
`<input type="text" name="input-data-pedido" placeholder="Insira a data do pedido" required>`

por isso
`<input type="date" name="input-data-pedido" placeholder="Insira a data do pedido" required>`

**Comment by TiagoSousaF** [comment]
Issue consertada, só preciso fazer o commit.
